import csv
import os
from concurrent.futures import ProcessPoolExecutor
import numpy as np
from scipy.stats import norm
from adaptive_importance_sampling import run_simulation
import config as cfg

def read_csv(filename):
    """
    Reads the parameter data from a CSV file generated by adaptive importance sampling.

    Args:
        filename (str): The path to the CSV file.

    Returns:
        np.ndarray: A NumPy array containing the parameter values from each iteration,
                    excluding the iteration number.
    """
    data = []
    try:
        with open(filename, mode='r', newline='') as file:
            reader = csv.reader(file)
            next(reader)  
            for row in reader:
                if row:
                    data.append([float(x) for x in row])
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return np.empty((0, 0))

    return np.array(data)

def get_probability_estimate(params_history, mode_idx, num_samples=50):
    """
    Estimates failure probability using Importance Sampling:
    P_fail = (1/m) * sum( (p(x)/q(x)) * I(x is failure) )
    """

    # q is proposal
    mu_q = params_history[-1, 1:]
    mu_q = cfg.MU_Q
    # p is nominal distribution
    mu_p = cfg.MU_P

    sigma = np.abs(mu_p * 0.2)
    sigma[sigma < 0.1] = 0.1 
    

    samples = [np.random.normal(mu_q, sigma) for _ in range(num_samples)]
    print(f"Starting Importance Sampling with {num_samples} samples in parallel...")

    # Create safe clipped samples for simulation, but keep original for probability math
    safe_samples = []
    for x_i in samples:
        safe_x = x_i.copy()
        safe_x[0] = np.clip(safe_x[0], 0.0, 1.0)   # W_dist
        safe_x[1] = np.clip(safe_x[1], 0.0, 1.0)   # mu_dist
        safe_x[2] = max(0.01, safe_x[2])           # var_dist
        safe_x[3] = np.clip(safe_x[3], 0.0, 1.0)   # mu_wind
        safe_x[4] = max(0.01, safe_x[4])           # var_wind
        safe_x[5] = np.clip(safe_x[5], 0.0, 1.0)   # W_angle
        safe_x[6] = max(0.01, safe_x[6])           # var_wind_angle_change
        safe_samples.append(safe_x.tolist())

    with ProcessPoolExecutor() as executor:
        futures = [
            executor.submit(run_simulation, safe_x, i, 0, False)
            for i, safe_x in enumerate(safe_samples)
        ]
        results = [f.result() for f in futures]


    weights_times_indicator = []
    raw_failures = 0
    for x_i, result in zip(samples, results):
        failure_mode = result[0]
        # Indicator function based on failure mode
        is_failure = 0
        if mode_idx == 0:   # Total Cost
            if failure_mode == 1: is_failure = 1
        elif mode_idx == 1: # Total Time
            if failure_mode == 2: is_failure = 1
        elif mode_idx == 2: # Stuck Count
            if failure_mode == 3: is_failure = 1
            
        raw_failures += is_failure
            
        # Calculate likelihood ratio: w = p(x_i) / q(x_i) and use log-space for numerical stability before exponentiating
        log_p = np.sum(norm.logpdf(x_i, mu_p, sigma))
        log_q = np.sum(norm.logpdf(x_i, mu_q, sigma))
        weight = np.exp(log_p - log_q)
        
        weights_times_indicator.append(weight * is_failure)
    # Weight Clipping
    weights_times_indicator = np.clip(weights_times_indicator, a_min=None, a_max=1.0)
    
    return np.mean(weights_times_indicator), (raw_failures / num_samples)

if __name__ == '__main__':
    failure_modes = ["Total Cost", "Total Time", "Stuck Count"]
    input_folder = "AIS_params_expert_start"

    for mode_idx, mode_name in enumerate(failure_modes):
        filename = os.path.join(input_folder, f"AIS_params_{mode_name.replace(' ', '_')}.csv")
        params_history = read_csv(filename)
        
        if params_history.size > 0:
            print(f"\n{'='*40}")
            print(f"Estimating Probability for: {mode_name}")
            print(f"{'='*40}")

            # The final set of parameters is the last row in the file
            final_params = params_history[-1, 1:]
            print(f"Final estimated parameters (mu):\n{final_params}")

            # Estimate the actual probability
            p_fail_nominal, p_fail_expert = get_probability_estimate(params_history, mode_idx)
            print(f"Estimated Probability of Failure (Nominal p): {p_fail_nominal:.6e}")
            print(f"Failure Rate of Proposal Distribution (Expert q): {p_fail_expert:.2%}")
