import csv
import numpy as np
from scipy.stats import norm
from adaptive_importance_sampling import run_simulation

def read_csv(filename):
    """
    Reads the parameter data from a CSV file generated by adaptive importance sampling.

    Args:
        filename (str): The path to the CSV file.

    Returns:
        np.ndarray: A NumPy array containing the parameter values from each iteration,
                    excluding the iteration number.
    """
    data = []
    try:
        with open(filename, mode='r', newline='') as file:
            reader = csv.reader(file)
            next(reader)  
            for row in reader:
                if row:
                    # Store the full row including Iteration and all params
                    data.append([float(x) for x in row])
    except FileNotFoundError:
        print(f"Error: File '{filename}' not found.")
        return np.empty((0, 0))

    return np.array(data)

def get_probability_estimate(params_history, num_samples=50):
    """
    Estimates failure probability using Importance Sampling:
    P_fail = (1/m) * sum( (p(x)/q(x)) * I(x is failure) )
    """
    # 1. Define distributions
    # q is our proposal (the final optimized parameters from AIS)
    mu_q = params_history[-1, 1:]
    # p is our nominal distribution (the first iteration parameters)
    mu_p = params_history[0, 1:]
    
    # Use a consistent standard deviation for the likelihood evaluation.
    # AIS uses a search width; we'll use a 20% spread for the probability densities.
    sigma = np.abs(mu_p * 0.2) + 1e-6 

    m = num_samples
    weights_times_indicator = []

    print(f"Starting Importance Sampling with {m} samples...")

    for i in range(m):
        # Sample a candidate disturbance vector from the proposal distribution q
        x_i = np.random.normal(mu_q, sigma)
        
        # Run simulation (render=0 for speed)
        # Returns [total_cost, total_time, stuck_count]
        result = run_simulation(None, x_i.tolist(), trial_num=i, render=0, save_data=False)
        stuck_count = result[2]
        
        # Indicator function: 1 if failure occurs (Stuck Count >= 10), else 0
        is_failure = 1 if stuck_count >= 10 else 0
        
        # Calculate likelihood ratio: w = p(x_i) / q(x_i)
        # We use log-space for numerical stability before exponentiating
        log_p = np.sum(norm.logpdf(x_i, mu_p, sigma))
        log_q = np.sum(norm.logpdf(x_i, mu_q, sigma))
        weight = np.exp(log_p - log_q)
        
        weights_times_indicator.append(weight * is_failure)

    return np.mean(weights_times_indicator)

if __name__ == '__main__':
    filename = "AIS_params_Stuck_Count.csv"
    params_history = read_csv(filename)
    
    if params_history.size > 0:
        print("Successfully read parameters history:")
        print(params_history)

        # The final set of parameters is the last row in the file
        final_params = params_history[-1]
        print("\nFinal estimated parameters (mu):")
        print(final_params)

        # Estimate the actual probability
        p_fail = get_probability_estimate(params_history)
        print(f"\nEstimated Probability of Failure: {p_fail:.6e}")
